services:
  client:
    container_name: dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: bash -c "npm install && npm run dev"
  api:
    container_name: dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=cohabit
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=trackerDB
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=trackerDB
      - POSTGRES_USER=cohabit
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
